import Head from 'next/head'
const Header = () => {
    return (
        <Head>
        <title>Guest House Feedback Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
    )
}
export default Header